### PR TITLE
Update: Updated the PageNotExist 

### PR DESCRIPTION
**Pull request by mohammadruman**
#258 Issue solved
This pull request updates the "Page Not Found" page to enhance user experience and provide clearer navigation options.

### Changes Made:
The previous error message has been replaced with a more user-friendly notification. The new message now reads:
**"Feature will be soon available."**
image

### CODE REVIEW

**Comment by NayakPenguin** [comment]
Thank you, @mohammadruman, for the pull request. However, a few improvements are needed:

1. Please refrain from altering the existing 404 Not Found page; instead, create a new "Feature Coming Soon" page and link it accordingly.
2. Design a new UI; do not use the UI from the 404 Not Found page.

**Review by mohammadruman — COMMENTED** [review]
Updated the Changes accordingly

**Comment by NayakPenguin** [comment]
Great work @mohammadruman! 🎉
Code is clean and works as expected 🚀

**Comment by mohammadruman** [comment]
Thank you so much! I'm glad the code meets expectations. I'm excited to contribute more to the project

**Pull request merged**
