### PR TITLE
feat: implement localStorage for button status tracking

### PR DESCRIPTION
**Pull request by MehekFatima**
This pull request introduces functionality to track the status of three buttons ("Filled," "Not Interested," and "Liked") using `localStorage`.

### CODE REVIEW

**Comment by NayakPenguin** [comment]
Great job, @MehekFatima! 🎉

Your implementation of localStorage for tracking button status works perfectly and enhances the user experience by preserving selections across sessions. Thanks for the clean and efficient solution!

Just a minor note—the line between "Opportunity" and "Track" is missing, but it's a small issue, so no worries.

Screenshot 2024-10-12 at 1 24 54 AM

Screenshot 2024-10-12 at 1 25 11 AM

The code looks very clean, thank you for the contribution, @MehekFatima! 🎉
Merging this now 🚀

**Comment by MehekFatima** [comment]
Thank you for the feedback! I'll add that missing line in the next update if you want.

**Comment by NayakPenguin** [comment]
@MehekFatima thanks that would be great!

**Comment by MehekFatima** [comment]
Great! Could you please assign me the issue so I  work on it for the next update? @NayakPenguin

**Comment by NayakPenguin** [comment]
Hi @MehekFatima, please go ahead and create the issue—I'll be happy to assign it to you.

**Comment by MehekFatima** [comment]
Hi, I've created the issue as requested.

**Pull request merged**
